spring:
  application:
    name: rpc-consumer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
mantis:
  protocols:
    - type: mantis
      port: 23332

#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
server:
  port: 8082
logging:
  level:
    io.github.astro: debug
