spring:
  application:
    name: rpc-provider
  config:
    import: classpath:/mantis/mantis-application.yml
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}

#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
server:
  port: 8081
logging:
  level:
    io.github.astro: debug

